### ISSUE TITLE
API for Hecke matrices

### ISSUE THREAD

**Issue by kedlaya** [jefferyphein/ternary-birch#1]
With a bit of guidance from John V., I managed to compile this code. It is impressively fast!

I'm trying to write a Cython wrapper to transport Hecke matrices into Sage. However, besides the print function, currently the only exposed functionality for extracting data out of the Hecke matrices is the number of rows. I will eventually hack my local install to expose the underlying matrix, but if you have a preferred mechanism for achieving that goal (e.g., providing access functions instead of moving the underlying data structure from private to public) I can easily adapt to that.

**Comment by jefferyphein** [comment]
This should be largely addressed with the newest push. I've added a few accessor methods to SparseMatrix ("at" and "data"), HeckeOperator ("at" and "matrix"), and Genus ("hecke_operator"), to allow for constant reference access to the underlying computed Hecke operator data.
